# Generated by Django 4.1.5 on 2023-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resrent',
            name='files',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
