# Generated by Django 4.1.5 on 2023-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0002_resrent_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrent',
            name='files',
            field=models.FileField(null=True, upload_to='img/upload/'),
        ),
    ]
