# Generated by Django 4.1.5 on 2023-01-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residant',
        ),
    ]
