# Generated by Django 4.1.5 on 2023-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0005_alter_resrent_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='residant',
            name='rate',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
