# Generated by Django 4.1.5 on 2023-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_owner',
            fields=[
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=8)),
                ('phn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=100)),
                ('psword', models.CharField(max_length=40)),
                ('p_addrs', models.CharField(max_length=200)),
                ('div', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('nid', models.CharField(max_length=20)),
                ('hid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pro_owner',
            },
        ),
        migrations.AlterField(
            model_name='residant',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
