# Generated by Django 4.1.5 on 2023-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_pro_owner_alter_residant_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='residant',
            name='about_me',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='residant',
            name='per_addrs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residant',
            name='uname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
