# Generated by Django 4.1.5 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_pro_owner_picc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_owner',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pro_owner',
            name='twofact',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
