# Generated by Django 4.1.5 on 2023-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0008_residant_about_me_residant_per_addrs_residant_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('comID', models.IntegerField(primary_key=True, serialize=False)),
                ('slv_status', models.CharField(max_length=20)),
                ('prob_type', models.CharField(max_length=50)),
                ('prob_desc', models.CharField(max_length=200)),
                ('nei_ID', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'complain',
            },
        ),
    ]
