# Generated by Django 4.1.5 on 2023-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0008_pro_owner_otp_pro_owner_twofact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_owner',
            name='otp',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
