# Generated by Django 4.1.5 on 2023-01-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0009_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='rm.residant'),
            preserve_default=False,
        ),
    ]
