# Generated by Django 4.1.5 on 2023-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0010_complain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='nei_ID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='slv_status',
            field=models.CharField(default='not solved', max_length=20),
        ),
    ]
