# Generated by Django 4.1.5 on 2023-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0011_alter_complain_nei_id_alter_complain_slv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='comID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
