# Generated by Django 4.1.5 on 2023-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0012_alter_complain_comid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='slv_status',
            field=models.CharField(default='Not Solved', max_length=20),
        ),
    ]
