# Generated by Django 4.1.5 on 2023-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0012_apartment_bath_apartment_bed_apartment_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='active_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
