# Generated by Django 4.1.5 on 2023-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0013_alter_complain_slv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
