# Generated by Django 4.1.5 on 2023-05-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0013_alter_activity_active_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picss', models.ImageField(null=True, upload_to='advers/')),
                ('apart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rm.apartment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rm.pro_owner')),
            ],
            options={
                'db_table': 'advertisment',
            },
        ),
    ]
