# Generated by Django 4.1.5 on 2023-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0014_alter_complain_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='year',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
