# Generated by Django 4.1.5 on 2023-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0014_advertisment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='adver',
            field=models.CharField(default='NO', max_length=5),
        ),
    ]
