# Generated by Django 4.1.5 on 2023-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0015_apartment_adver'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bill',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
