# Generated by Django 4.1.5 on 2023-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0015_complain_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='nei_ID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
