# Generated by Django 4.1.5 on 2023-02-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0016_alter_complain_nei_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResRent',
            fields=[
                ('amount', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='NOT PAID', max_length=30, null=True)),
                ('deadline', models.CharField(default='none', max_length=40, null=True)),
                ('month', models.CharField(default='none', max_length=30, null=True)),
                ('paymentID', models.CharField(default='none', max_length=100)),
                ('date', models.CharField(default='0-0-0000', max_length=50, null=True)),
                ('uniqID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='rm.residant')),
            ],
            options={
                'db_table': 'residantrent',
            },
        ),
    ]
