# Generated by Django 4.1.5 on 2023-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0016_apartment_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='waitforapproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('nid', models.CharField(max_length=50, null=True)),
                ('apps', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'waitforapproval',
            },
        ),
    ]
