# Generated by Django 4.1.5 on 2023-02-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0017_resrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(default=' ', max_length=400, null=True)),
                ('date', models.CharField(default=' ', max_length=30, null=True)),
                ('user_id', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='rm.residant')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
