# Generated by Django 4.1.5 on 2023-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0017_waitforapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitforapproval',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
