# Generated by Django 4.1.5 on 2023-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0018_waitforapproval_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitforapproval',
            name='id',
        ),
        migrations.AlterField(
            model_name='waitforapproval',
            name='apps',
            field=models.CharField(default='--', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
