# Generated by Django 4.1.5 on 2023-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0019_rename_user_id_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(default='unread', max_length=60),
        ),
    ]
