# Generated by Django 4.1.5 on 2023-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0020_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='bill',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
