# Generated by Django 4.1.5 on 2023-03-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0020_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='residant',
            name='authheticate',
            field=models.CharField(default='NO', max_length=500),
        ),
    ]
