# Generated by Django 4.1.5 on 2023-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0021_advertisment_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='bathroom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='bed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='kitchen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='lroom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
