# Generated by Django 4.1.5 on 2023-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0022_residant_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.IntegerField(null=True)),
                ('last_login', models.CharField(max_length=100, null=True)),
                ('side_activity', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rm.residant')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
