# Generated by Django 4.1.5 on 2023-05-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0022_advertisment_address_advertisment_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='rating',
        ),
    ]
