# Generated by Django 4.1.5 on 2023-03-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0024_activity_last_log_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activ_time', models.CharField(max_length=100, null=True)),
                ('msg', models.CharField(max_length=140, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rm.residant')),
            ],
            options={
                'db_table': 'otherActivity',
            },
        ),
    ]
