# Generated by Django 4.1.5 on 2023-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0025_otheractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resrent',
            name='image',
            field=models.ImageField(default='null', upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
