# Generated by Django 4.1.5 on 2023-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0026_resrent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resrent',
            name='image',
        ),
        migrations.AddField(
            model_name='residant',
            name='image',
            field=models.ImageField(default='null', upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
