# Generated by Django 4.1.5 on 2023-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0027_remove_resrent_image_residant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residant',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
