# Generated by Django 4.1.5 on 2023-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0028_alter_residant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residant',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
