# Generated by Django 4.1.5 on 2023-04-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0029_alter_residant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(default='0', max_length=100)),
                ('commnt', models.CharField(default='', max_length=300)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rm.pro_owner')),
                ('residnt', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rm.residant')),
            ],
            options={
                'db_table': 'ratting',
            },
        ),
    ]
